image: ubuntu:latest
stages:
  - build
  - test
  - code_quality
  - deploy


code_quality:
  stage: code_quality
  variables:
    UPLOAD_QUALITY_REPORT: 'curl -X PUT -H "Authorization:Token $QSCORED_API_KEY" -H "repository-link: $CI_PROJECT_URL" +  -H "username: hr637632@dal.ca" -H "Content-Type: mulitpart/form-data" --url "https://qscored.com/api/upload/file.xml?is_open_access=false&version=$CI_PIPELINE_IID&project_name=group20" -F "file=@Designite_output/DesigniteAnalysis.xml"'

  before_script:
    - apt-get update
    - ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
    - apt-get --yes --force-yes install wget curl maven git

  script:
    - wget -O DesigniteJava.jar https://www.dropbox.com/s/mwizkj8uhplz4x3/DesigniteJava.jar?dl=1
    - echo "$Designite_output"
    - java -jar DesigniteJava.jar -i . -o Designite_output/ -f XML
    - ls Designite_output
    - 'eval "$UPLOAD_QUALITY_REPORT"'
  only:
    refs:
      - main
      - develop
      - test-app

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn compile -B
  only:
    refs:
      - main
      - test-app
      - develop
      - merge_requests
      - feature-admin-pipeline
      - feature-frontend
      - feature-backend


maven-test:
  image: maven:3-jdk-8
  stage: test
  script: mvn test -B
  only:
    refs:
      - main
      - develop
      - test-app
      - merge_requests
      - feature-admin-pipeline
      - feature-frontend
      - feature-backend

deploy-prod:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=app-staff-scheduler --api-key=$HEROKU_API_KEY
  only:
    refs:
      - main

deploy-dev:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=app-staff-scheduler-dev --api-key=$HEROKU_API_KEY
  only:
    refs:
      - develop

deploy-test:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=app-staff-scheduler-test --api-key=$HEROKU_API_KEY
  only:
    refs:
      - test-app