stages:
  - build
  - test
  - deploy

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn package -B"

maven-test:
  image: maven:3-jdk-11
  stage: test
  script: "mvn test -B"

deploy:
  stage: deploy
  image: ruby:latest
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=app-staff-scheduler --api-key=$HEROKU_API_KEY
  only:
  - master
